---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-store-sa
  namespace: secret-store
  annotations:
    azure.workload.identity/client-id: 1b717d03-8a56-467b-a77b-eae4e853ec61
    azure.workload.identity/tenant-id: bb73082a-b74c-4d39-aec0-41c77d6f4850
    
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akv-backend
  namespace: secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-opencti-we-597f.vault.azure.net/"
      serviceAccountRef:
        name: secret-store-sa
        namespace: secret-store