apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencti-minio-sa
        namespace: opencti-minio
        annotations:
          azure.workload.identity/client-id: 202c13b6-a51e-4db7-9c99-b0522a7c8347
        labels:
          azure.workload.identity/use: "true"
    target:
      kind: ServiceAccount
      name: opencti-minio-sa
      namespace: opencti-minio