apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml
- networkpolicy.yaml

# patches:
#   - patch: |-
#       apiVersion: v1
#       kind: ServiceAccount
#       metadata:
#         name: opencti-minio-sa
#         namespace: opencti-minio
#         annotations:
#           azure.workload.identity/client-id: 6745772f-fc78-4c40-92ed-1f1924c9e067
#         labels:
#           azure.workload.identity/use: "true"
#     target:
#       kind: ServiceAccount
#       name: opencti-minio-sa
#       namespace: opencti-minio