apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencti-minio-sa
        namespace: opencti-minio
        annotations:
          azure.workload.identity/client-id: 046748e0-ab09-469b-8415-5b2029ffc7e8
        labels:
          azure.workload.identity/use: "true"
    target:
      kind: ServiceAccount
      name: opencti-minio-sa
      namespace: opencti-minio