apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencti-minio-sa
        namespace: opencti-minio
        annotations:
          azure.workload.identity/client-id: 88466e0c-cd29-4635-9bf5-877b316c5c9a
        labels:
          azure.workload.identity/use: "true"
    target:
      kind: ServiceAccount
      name: opencti-minio-sa
      namespace: opencti-minio