apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencti-minio-sa
        namespace: opencti-minio
        annotations:
          azure.workload.identity/client-id: 7271ff27-7e12-483b-9962-826ab1bdb9a0
        labels:
          azure.workload.identity/use: "true"
    target:
      kind: ServiceAccount
      name: opencti-minio-sa
      namespace: opencti-minio