apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencti-minio-sa
        namespace: opencti-minio
        annotations:
          azure.workload.identity/client-id: 6e9a9921-5e91-4157-b421-0061409d34b0
        labels:
          azure.workload.identity/use: "true"
    target:
      kind: ServiceAccount
      name: opencti-minio-sa
      namespace: opencti-minio