apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- minio.yaml
- networkpolicy.yaml

# patches:
#   - patch: |-
#       apiVersion: v1
#       kind: ServiceAccount
#       metadata:
#         name: opencti-minio-sa
#         namespace: opencti-minio
#         annotations:
#           azure.workload.identity/client-id: eefb77e4-3bec-4c5d-be25-eebeb242c6a0
#         labels:
#           azure.workload.identity/use: "true"
#     target:
#       kind: ServiceAccount
#       name: opencti-minio-sa
#       namespace: opencti-minio