---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-secret
  namespace: opencti-minio
spec:
  secretStoreRef:
    name: akv-backend
    kind: ClusterSecretStore
  refreshInterval: "10m"
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-root-user
    - secretKey: rootPassword
      remoteRef:
        key: minio-root-password
---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: opencti-minio-secretprovider # needs to be unique per namespace
#   namespace: opencti-minio
# spec:
#   provider: azure
#   secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
#   - data:
#     - key: rootUser
#       objectName: minio-root-user
#     - key: rootPassword
#       objectName: minio-root-password
#     secretName: minio-root-secret
#     type: Opaque
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "false"          
#     clientID: "f9d92e71-c895-4b7f-94a3-58e09a2297d7"
#     keyvaultName: demo-aks-westeu-9599
#     tenantId: "bb73082a-b74c-4d39-aec0-41c77d6f4850"
#     objects:  |
#       array:
#         - |
#           objectName: minio-root-user
#           objectType: secret
#         - |
#           objectName: minio-root-password
#           objectType: secret
# ---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: opencti-minio
spec:
  interval: 1h0s
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: opencti-minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: '5.0.13'
  interval: 1h0s
  releaseName: minio
  targetNamespace: opencti-minio
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      storageClass: azurefile-csi-opencti
      size: 5Gi
    replicas: 3
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    networkPolicy:
      enabled: true
      allowExternal: false
    existingSecret: minio-root-secret
    tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: In
              values:
              - "spot"
    postJob:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                - "spot"    
    # serviceAccount:
    #   create: true
    #   name: opencti-minio-sa
    # podLabels:
    #   azure.workload.identity/use: "true"
    # extraVolumeMounts:
    #   - name: secrets-store01-inline
    #     mountPath: "/mnt/secrets-store"
    #     readOnly: true
    # extraVolumes:
    #   - name: secrets-store01-inline
    #     csi:
    #       driver: secrets-store.csi.k8s.io
    #       readOnly: true
    #       volumeAttributes:
    #         secretProviderClass: "opencti-minio-secretprovider"
---