---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: opencti-minio-secretprovider # needs to be unique per namespace
  namespace: opencti-minio
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: rootUser
      objectName: minio-root-user
    - key: rootPassword
      objectName: minio-root-password
    secretName: minio-root-secret
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "21a508e3-67e1-45a7-9984-24ce4c685682"
    keyvaultName: demo-aks-westeu-0a7b
    tenantId: "bb73082a-b74c-4d39-aec0-41c77d6f4850"
    objects:  |
      array:
        - |
          objectName: minio-root-user
          objectType: secret
        - |
          objectName: minio-root-password
          objectType: secret
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: opencti-minio
spec:
  interval: 1h0s
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: opencti-minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: '>=5.0.9'
  interval: 1h0s
  releaseName: minio
  targetNamespace: opencti-minio
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      storageClass: azurefile-csi-opencti
      size: 5Gi
    replicas: 3
    resources:
      requests:
        memory: 1Gi
    existingSecret: minio-root-secret
    serviceAccount:
      create: true
      name: opencti-minio-sa
    podLabels:
      azure.workload.identity/use: "true"
    extraVolumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
    extraVolumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "opencti-minio-secretprovider"
---