---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: opencti-minio
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow
  namespace: opencti-minio
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postjob-egress
  namespace: opencti-minio
spec:
  podSelector:
    matchLabels:
      app: minio-job
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: minio
    ports:
    - port: 9000
  ingress:
  - to:
    - podSelector:
        matchLabels:
          app: minio
    ports:
    - port: 9000
