---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: opencti-minio
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow
  namespace: opencti-minio
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: "0.0.0.0/0" # Allow egress out of the cluster
        except: # Deny egress to pods inside the Kubernetes private network
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inter-node-traffic
  namespace: opencti-minio
spec:
  podSelector:
    matchLabels:
      app: 
      - minio-post-job
      - minio
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - port: 6379
    - port: 16379 # clustering
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - port: 6379
    - port: 16379 # clustering