---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: opencti-redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: opencti-redis
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    #sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: opencti-redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext: 
        runAsUser: 999
        runAsGroup: 999 
        fsGroup: 999
        runAsNonRoot: true
      containers:
      - name: redis
        image: redis:7.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: gossip
#        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: redis-pvc
          mountPath: /data
          readOnly: false
        - name: conf
          mountPath: /conf
          readOnly: false
        securityContext: 
          runAsUser: 999 
          runAsGroup: 999 
          fsGroup: 999
          runAsNonRoot: true
      volumes:
      - name: conf
        configMap:
          name: redis-cluster
          defaultMode: 0755
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                - "spot"
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: redis
        maxSkew: 1
        topologyKey: kubernetes.azure.com/agentpool
        whenUnsatisfiable: ScheduleAnyway
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: azurefile-csi-opencti-uid999
      resources:
        requests:
          storage: 5Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis
  namespace: opencti-redis
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: redis
