---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: opencti-redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: opencti-redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: gossip
      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                - "spot"
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: redis
        maxSkew: 1
        topologyKey: kubernetes.azure.com/agentpool
        whenUnsatisfiable: ScheduleAnyway
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: azurefile-csi-opencti
      resources:
        requests:
          storage: 5Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis
  namespace: opencti-redis
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: redis
