---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencti-serviceaccount
  namespace: opencti
  annotations:
    azure.workload.identity/client-id: c19b34b6-4eee-4e8c-a133-94439a3c4835
  labels:
    azure.workload.identity/use: "true"
