---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: c19b34b6-4eee-4e8c-a133-94439a3c4835
  labels:
    azure.workload.identity/use: "true"
  name: opencti-sa
  namespace: opencti
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity # needs to be unique per namespace
  namespace: opencti
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: opencti-admin-email                           # data field to populate
      objectName: opencti-admin-email                        # name of the mounted content to sync; this could be the object name or the object alias
    secretName: opencti-secret                     # name of the Kubernetes secret object
    type: Opaque                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "c19b34b6-4eee-4e8c-a133-94439a3c4835" # Setting this to use workload identity
    keyvaultName: demo-aks-westeu-9ce2       # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: opencti-admin-email
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
  namespace: opencti
  labels:
    azure.workload.identity/use: true
spec:
  serviceAccountName: opencti-sa
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-1 
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: opencti-secret
            key: opencti-admin-email
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-workload-identity"