apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencti-storage
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/infra/storage
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  dependsOn: 
    - name: secret-store
