# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://demo-aks-westeu-9ce2.vault.azure.net/keys/sops-key/056b01270a22403597f048db2a26a3de