# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://demo-aks-westeu-898b.vault.azure.net/keys/sops-key/f88d5dd6db894b46a33fbf92cad0543d