# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://demo-aks-westeu-30cf.vault.azure.net/keys/sops-key/d67204fe573d492bb04471015dc3fb22