# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://demo-aks-westeu-e84a.vault.azure.net/keys/sops-key/1f07eae87ef64c3fad12b12c5934e3ba