# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://kv-opencti-we-913a.vault.azure.net/keys/sops-key/c69b1c221a1549c986958156f3d3b482