# .sops.yaml
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://kv-opencti-we-597f.vault.azure.net/keys/sops-key/3fcf9cedae114e17af29f2cfb94cbe2b