apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-config-secret
    namespace: opencti-elasticsearch
type: Opaque
stringData:
    bootstrap.password: ENC[AES256_GCM,data:LCSpM6aDrRJEtKI/r60mCz1vkQ==,iv:KObnhaYiE1xEVfAN6YNP7z50wvA0wC3ysfqEDAJ+5KU=,tag:sW5uwEvcjRZvTuH2vrdn1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-a35b.vault.azure.net
          name: sops-key
          version: 4a8c8ec42463415eadb29dfe6de34a06
          created_at: "2023-08-09T07:20:41Z"
          enc: d1eIzfz7kw_X5PvDuf0hLYj3DxMwmq1ZbE-t77LbQBG9940UsaExVYZNx2OGdOM5BCjInxBf_ED--0u0JO6I0YreiNDsh49AOviWDJsnQWUhnlobCBKuhpjn8CR9fktU2CCb0mvWHjW4_x84zm_Ba0-jDb_FBylHlDpPMSEh_NH-ox7gx4mSv9BO78q7ED0Sj-fWnBLknjgKtgCk9gLZGZUhN9hzFo6agVRYWmdzc3mvNK7lWnkjFrt1ZxK0SEIxI8B_xKQiCikISWsWHengoxnxw0ZRGuPEo2ZnA0LmQwFhRylXcIc-0YNMsJPAMNXZa8R8t0X9LtZnwEPs-ss3NA
    hc_vault: []
    age: []
    lastmodified: "2023-08-09T07:20:42Z"
    mac: ENC[AES256_GCM,data:UThZaD6QRM/hxsRzby4zBpRo8vId2kh0aBRJ7SgDhw3RKQD2AbbuFZm0y2ufVY7JJWleS14gmvroczuggSIlYJLJd4YC7b23FTIxclar/wn8PKOIK57udE980xWaQHGqhp9TNbVsy48LcbXghKuODad9P1rFem/tHJjtCtTLnFw=,iv:HOCuR113tUNHjphR4kMU4NkMwWCRYTtiK9zGMelRc5I=,tag:BTKPak8nO7kyAdPGwsN5Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
