---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: external-dns
spec:
  secretStoreRef:
    name: akv-backend
    kind: ClusterSecretStore
  refreshInterval: "10m"
  target:
    template:
      data:
        azure.json: |
          {
            "tenantId": "{{ .azuretenantid }}",
            "subscriptionId": "{{ .azuresubscriptionid }}",
            "resourceGroup": "{{ .azurereourcegroupname }}",
            "useManagedIdentityExtension": true
          }
  data:
    - secretKey: azuretenantid
      remoteRef:
        key: azuretenantid
    - secretKey: azuresubscriptionid
      remoteRef:
        key: azuresubscriptionid
    - secretKey: azurereourcegroupname
      remoteRef:
        key: azurereourcegroupname
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: '>=1.13.0'
  interval: 1h0s
  releaseName: external-dns
  targetNamespace: external-dns
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    provider: azure
    serviceAccount:
      name: external-dns-sa
      labels:
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/client-id: 90421a2b-00c8-4795-9fd6-2df88ee3724e
    podAnnotations:
      azure.workload.identity/inject-proxy-sidecar: "true"
    podLabels:
      azure.workload.identity/use: "true"
    domainFilters:
      - k8s.4t2.no
    extraVolumes:
      - name: azure-credentials
        secret:
          secretName: external-dns-secret
    extraVolumeMounts:
      - name: azure-credentials
        mountPath: /etc/kubernetes
        readOnly: true
    # secretConfiguration:
    #   enabled: true
    #   mountPath: /etc/kubernetes
    #   data:
    #     azure.json: |
    #       {
    #         "tenantId": "bb73082a-b74c-4d39-aec0-41c77d6f4850",
    #         "subscriptionId": "e5183437-65de-4900-9987-9b9ff0fae0a3",
    #         "resourceGroup": "demo-aks-westeu",
    #         "useManagedIdentityExtension": true
    #       }
---