apiVersion: v1
kind: Secret
metadata:
    name: azure-storage-account-opencti-secret
    namespace: opencti-storage
type: Opaque
stringData:
    azurestorageaccountname: ENC[AES256_GCM,data:fxq4DkY3gW7QaKAu+BKv4mrVGw==,iv:DyGVrMdl3yhumjslS/DrhThU313LDvUDjOobu/OgenY=,tag:DpNQfnHomTtZ91bpYF6XIw==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:mujT5Qez67s127ed44gfVUvk3mHoGlgxlHhxkFOLK0lqS+nFZ3pehBmIFDOPmIDNq3mLG2iygGXGaRVVOUXs+IKYBYdgNUCrpZ/+H1HthDLEpdott+Xaxw==,iv:XSV7EecTDyT4p8LXfatrkm2LuPtGrbMzkK83M8sjUE4=,tag:Iylv5FR/jVoB8enQwEdKYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-9ce2.vault.azure.net
          name: sops-key
          version: 056b01270a22403597f048db2a26a3de
          created_at: "2023-08-03T08:46:27Z"
          enc: tTY4pjA_WqFHjtOEfoFd7MceC7M0rVnm_qjNoUZ6kHuhbKOIkjJnvoM2pyqfoW5l1JXpEUj4eKcyieRfaWQfngx0F5-YWuQIghBThKBeD-ysP16u0lysotwX6c3-acNWTaXb6lv6MlKAeIK1W9xw55OeXabRVZlbWEKcXR9OeAtyLB5NdikP4zXw01tpb_7FAe4QCN7ltAEF2Y1eP3yohLd2wDcz20qnT5FY486vDVR9R5e-Mn6n2oaaMihFQgiamQd-LyWU2vdvpb0z45QOh9Yk83Iu0DYQJ50Qqu6jclu_etB2SopbF6fQzvFCqoT2XYA1CP5N0MkCPOFvd9sEmw
    hc_vault: []
    age: []
    lastmodified: "2023-08-03T08:46:28Z"
    mac: ENC[AES256_GCM,data:oEZ51efwh3lXCgIrH9bmeJnLr4zq54Vjbxf7ZqzsKYybm+SSplJwfLkLwmboW38111ymb0hGtT07s2UDzZK2fZ71mE5WWj0sKK7oE4so8fJERnQZuHVmL2J3m99QHm6VdDgDp8tt+Lpi9OyHpUXFdJNIt39iBTDgINrQBjS/daY=,iv:sGm0dkXKDhCbIfq7KwurbkhiuCueU55kXgdUSBtV8uc=,tag:jmYMOO0YK6EJxYbV53Wa5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
