apiVersion: v1
kind: Secret
metadata:
    name: azure-storage-account-opencti-secret
    namespace: opencti-storage
type: Opaque
stringData:
    azurestorageaccountname: ENC[AES256_GCM,data:YH/MVYDZXD/s1TGBJj+3ey4+8g==,iv:CJjNdGbIFUN1hFaA3g2sR5A7CKv9GKZW4c2eFqQ+WsA=,tag:E3YKPPfwKZHBMveZA+QvWQ==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:pSIJ2v9NvzsC3yGcK+bC9bvNXD7U0jx4pfHBmSd4d2s1RobxCxnPrLHKUGFWW/ibEU2fuqbmrO2B4+22HiZjSw1DUyYNGWrKrbUb7YkVrATtwZQ8gWqFNw==,iv:pJ+OyKUPj6tP8cOAnThH/IgcIiZe91j5X7oO9zGPbQg=,tag:fxNC9jqD0gyvKvNdzup8rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-2719.vault.azure.net
          name: sops-key
          version: f7d7286944744447a838eb7366c6eb34
          created_at: "2023-08-04T06:47:03Z"
          enc: maK9J4l0TuMS_v3xkOy8id5a552ow6dLEPITUmqKwDLJRPeOpK5DqChuOjI9ArtLikBV_sAhkR3eou4iJOegqMa0iEThLV2-g9DOTAw--cGTBAsfyMH7qN_e_68tnnS1djmu0Ukk3wVf73JJIFdM495JzjPnalXy0Ijfw0pUy6sBnvRVo9C-0D7ybJseSDLKbMb5uZ-UFDqnbTYXUGza9RiJKQDvE0dApckynKrUvvCB6uoilHE0g62N3OLzRLr6WYKQiDKFhp6Ijp9b94F13JZMmB4eufKol1zDtjiEYykv0ivJRgyIAvJZvZthYstvBErubdzNSpPYWBaCy0xtJA
    hc_vault: []
    age: []
    lastmodified: "2023-08-04T06:47:04Z"
    mac: ENC[AES256_GCM,data:OAD6LCLwohJ4LgpFafb2EjRPNT5Dqoedbt3LAbYSLJz14lVkQldCQwI4DJHxQsAMTiwmPKZ9kSQ+BV1TOpZuhfwr7wb6C1q44neCDwnCJsEmifbk4IVcLhWtvzdcNMBV9PnK7WkReF0GDRf95WPRZ9Fg4qXTjshhCHXl8spp57k=,iv:3GeVRWeZvNPOkiNkl+UfSHni8XXGx7pKeXeBbAuyWiI=,tag:l2FjCSBQogS0sEgzXn220g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
