---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic
  namespace: elastic-system
spec:
  interval: 1h0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
      version: '>=2.8.0'
  interval: 1h0s
  releaseName: elastic-operator
  targetNamespace: elastic-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      validateStorageClass: false
    webhook:
      enabled: false
---