apiVersion: v1
kind: Secret
metadata:
    name: azure-storage-account-opencti-secret
    namespace: opencti-storage
type: Opaque
stringData:
    azurestorageaccountname: ENC[AES256_GCM,data:aoMujpTkFsueyPEpV7ODVrWR0g==,iv:CDWV6DKE0c17miubKUPOSfA1403lgR8cj1COiuPMIpk=,tag:Zd4alKd16Mmwb83VYTEpQg==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:iMoetZ0yt8Cl5d2sC20miSWhxmNLb1G4vPHIQDfBPS6MZeLMibfg7qZ8f41Nu1edOq1ffi71hi3YykKmbukLAvQ16qpl9au1mtd5SgECkoHNCVzZvoBecA==,iv:iN6/zXEsflepxjsaSHe1AZvOMGGugVrVHV9G2uhlC+k=,tag:ZhyxU/zbaCbrvq/MqN6RlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-bd7b.vault.azure.net
          name: sops-key
          version: 6aecda023be04888b6f51e7e8b507955
          created_at: "2023-08-07T11:18:05Z"
          enc: p5DFZA_v9gzF2AK5MKTuWTIM-l0ftkjlIO49wT0-f-NCP4FAbtN3REFiCorCbEMMLc-32eXMK45cvZ6f4uFS5kgpZam6YwXtwTbvW4V2wsYq2t20T5Tud4QpN3XVNLdiJhBQjfxWJNMyPDvmCcWQQMnTvsRhBHpJpd4sNJe6LQAlyP0U98NkLIOES8HkQaVJ330kugUOPP2RXgYBo_fLj9DThNsVboePyq-3Wh2Lf3GKesYzqsztkfs_rELVH81eb4yZwCm_dPwwqT7bcvh2L_azO6--10T8aGi_bpsWBaOcTyfcMT-v6s8MoiqIGIEBYsDL5xcZ8O2w2WR62h6hEw
    hc_vault: []
    age: []
    lastmodified: "2023-08-07T11:18:05Z"
    mac: ENC[AES256_GCM,data:QJ/5OhZ9EjeP19l/oEu6O0M0JmBbp6zrEnL8fYTTkHgUih2aRMcX82ImlR0f4rMMGuorxgN0RLC+czO0dzovc7UR8s2E+TaXNvH1ny2s1KIlQVspi/0pUzGTXvDh2J4yyFpfYK61AvkkSvVU/bGKuYyD7itn62F6YbVxDGjgVMM=,iv:2emZNxULq+U2j1Cz9CLMLEzHXjMNPw/kg+JbAUR8aXI=,tag:07w+c5IjMgcLFv8etKql/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
