#apiVersion: v1
#kind: Secret
#metadata:
#    name: azure-storage-account-opencti-secret
#    namespace: opencti-storage
#type: Opaque
#stringData:
#    azurestorageaccountname: x
#    azurestorageaccountkey: x
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-storage-account-opencti-secret
  namespace: opencti-storage
spec:
  secretStoreRef:
    name: akv-backend
    kind: ClusterSecretStore
  refreshInterval: "10m"
  data:
    - secretKey: azurestorageaccountname
      remoteRef:
        key: storageaccountname
    - secretKey: azurestorageaccountkey
      remoteRef:
        key: storageaccountkey
