apiVersion: v1
kind: Secret
metadata:
    name: azure-storage-account-opencti-secret
    namespace: opencti-storage
type: Opaque
stringData:
    azurestorageaccountname: ENC[AES256_GCM,data:RQqY9dl88oEiQ165RmhTeGraGQ==,iv:RcHTNyXGxMhxjKgJ1zififP4k0L6cQ55peUv9NqFNXk=,tag:ug8MgHpzUbIlo885HUEXRg==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:hV+eTw2za7R6ewWCMe8QuqcgB2DqZlazh+roHcGMA4UcFGAYNtx4FtAXt/J/neBbQODjgNalXry2sL94uXc1Snjw/mrVHVXGDxBV0LgzYd1ui/NQORvWrw==,iv:IOIgTi6Tkwb8dbgZOhUV0kxp7/4nDfDvDVLnJO0srf0=,tag:HTNARjv7VoITkNRegAYTjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-6be9.vault.azure.net
          name: sops-key
          version: 489c583bae5a4eae9d131adb1c4c0c34
          created_at: "2023-08-11T15:57:36Z"
          enc: NzGyhwaI5G0klPWXd_UGlIhHaO2UktR2oac_qKiOMRU5MDPpFvGVoOcxBatUGTtBV_2Pc6p2xlIA63SG4uxihALdeQ-WS5jM3kHIPbNWhH1uIw1RYmh1XUR2-kl4XFNbb4Ki-u6Dc885__eMyJspeaOp66MLgVjbfI5sp2n8IhpF9drUz5xJfd5P8pd6ZA2lav3dtq2T_Kdv-6yyMxU81SVY14YzZRu12bw7-2Fmhf4wYSwdW965h8tASDPAOz35BbMXwjsAhJ4riOMyJYWXWHfYV6qodO1zctwPXgQMBwHPFw9auDHMLuJSgjQiAu5znt1mrifuooRr2VfMMJolzA
    hc_vault: []
    age: []
    lastmodified: "2023-08-11T15:57:37Z"
    mac: ENC[AES256_GCM,data:rHeHPSVQR4D6GnWspyOWqY1IPXOaYmnQi2TyCwXVtz047B8d1i4yx+e2OG8wqQWrDpk7lM3vnpUzoE/K+3LfLRxJvvE6w6JNKUK70LJnsC5zyEbRmfeyNX/huxUeRJbFMaaLMOP/LlHWmquCZoE+LxkJ48ZFHnF6gaLjDWL0cz0=,iv:8/zAjzL0grDazupFkrv0Uiekrq0hAtvFGib+0ptZG7g=,tag:r+HfkRo6x/OW4vaiM6IkOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
