apiVersion: v1
kind: Secret
metadata:
    name: azure-storage-account-opencti-secret
    namespace: opencti-storage
type: Opaque
stringData:
    azurestorageaccountname: ENC[AES256_GCM,data:/JRgI/oJKUBZcFK91hNtdRzQRQ==,iv:NA1Zm1uXSFUeE6uy7OKU2hSpFhhuU2gnlo1W6Peq7s8=,tag:B0hfS4Kvdgj5WkUgf9cx1A==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:acnak17sjnjqZJh2NjZK/jW4zD/9QJOts/mLYYrJg3AS5+nYeg+vRXdb2e2tvYD0fmxGYPMPJXqHXBb+TX4LXXYyFGfa1NaDIG1ay8JsmgCT5iJ//k7AoQ==,iv:8wy9MjG8MP0vg0xbl/d51auwsviuorP3PKVgVCEte9o=,tag:ICFqma52S0dQxm693WdjTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-e84a.vault.azure.net
          name: sops-key
          version: 1f07eae87ef64c3fad12b12c5934e3ba
          created_at: "2023-08-14T08:14:34Z"
          enc: JlgxAoN5RAfYMVqH54D9OxzJIOFNswVBYecYuxSolcvvSlE-KaGXDF1HLeMZ9kCB3u4-lMIqGtej8li3nWefnru9IFAlQFUE7rbAG5Kjw3rs1ayjx3_yPhQ4VoZnEI7SHhI9OQEjj4PC3CRIgPVdMR5qcpYNn_NQmT07VQ6Qob6LYJYfdXDa_4YuXWfnoXSpZCdnVSwHo0PPLzzxRmPLZ9PxW5_JiZuTdtOJBc65RvEqhJqv9aTvYQlr-jVwm3fwxa3_SfnFUMdhRiLII9gZe0anxO6SQooj97jN0RYodJ3W2Aiw4iRuSVcvUklPcGyQdwFeZXdzAG84xtCexyx81g
    hc_vault: []
    age: []
    lastmodified: "2023-08-14T08:14:34Z"
    mac: ENC[AES256_GCM,data:6aDSBRST6R0pXBUPRDeHFghB2gBKtBtxlzqr6SkWq8mNUOwRDybZk333+Mds9w6553h106m2k8uU9dWyAD4V2Dl7q9yug7ovF0FG+D6/bMsFo6jI75hBEuqW7plNtDTcSOgGFZZQUXm8jctdgj4zTnsBD9tEJR5plVxraTKj178=,iv:9drPhmm/YPDDbjk35S3baCW95ZMyNqCkCXZNLFaXRSM=,tag:UEy5GLrzEy3KSXqaV2SVQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
