---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-opencti
  namespace: opencti-storage
allowVolumeExpansion: true
mountOptions:
  - mfsymlinks
  - actimeo=30
  - uid=1000
  - gid=1000
  - nosharesock
parameters:
  shareName: opencti-${pvc.metadata.name}
  secretName: azure-storage-account-opencti-secret
  secretNamespace: opencti-storage
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
#  skuName: Standard_LRS
#  storageAccount: stdemoakswesteue84a
#  resourceGroup: demo-aks-westeu