---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opencti-secret
  namespace: opencti
spec:
  secretStoreRef:
    name: akv-backend
    kind: ClusterSecretStore
  refreshInterval: "10m"
  data:
    - secretKey: opencti-base-url
      remoteRef:
        key: opencti-base-url
    - secretKey: opencti-config-issuer 
      remoteRef:
        key: opencti-config-issuer 
    - secretKey: opencti-config-clientid
      remoteRef:
        key: opencti-config-clientid
    - secretKey: opencti-config-secret 
      remoteRef:
        key: opencti-config-secret 
    - secretKey: opencti-config-redirect-uris
      remoteRef:
        key: opencti-config-redirect-uris
    - secretKey: opencti-admin-email
      remoteRef:
        key: opencti-admin-email
    - secretKey: opencti-admin-password
      remoteRef:
        key: opencti-admin-password
    - secretKey: opencti-token
      remoteRef:
        key: opencti-token
    - secretKey: rabbitmq-default-user
      remoteRef:
        key: rabbitmq-default-user
    - secretKey: rabbitmq-default-password
      remoteRef:
        key: rabbitmq-default-password
    - secretKey: minio-root-user
      remoteRef:
        key: minio-root-user
    - secretKey: minio-root-password
      remoteRef:
        key: minio-root-password
    - secretKey: elasticsearch-user
      remoteRef:
        key: elasticsearch-user
    - secretKey: elasticsearch-password
      remoteRef:
        key: elasticsearch-password
    - secretKey: alienvault-connector-id
      remoteRef:
        key: alienvault-connector-id
    - secretKey: opencti-connector-id
      remoteRef:
        key: opencti-connector-id
    - secretKey: alienvault-api-key
      remoteRef:
        key: alienvault-api-key
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: opencti-sa
#   namespace: opencti
#   annotations:
#     azure.workload.identity/client-id: 90421a2b-00c8-4795-9fd6-2df88ee3724e
#   labels:
#     azure.workload.identity/use: "true"
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kvname-workload-identity
#   namespace: opencti
# spec:
#   provider: azure
#   secretObjects:
#   - data:
#     - key: opencti-base-url
#       objectName: opencti-base-url 
#     - key: opencti-config-issuer 
#       objectName: opencti-config-issuer 
#     - key: opencti-config-clientid 
#       objectName: opencti-config-clientid 
#     - key: opencti-config-secret 
#       objectName: opencti-config-secret 
#     - key: opencti-config-redirect-uris 
#       objectName: opencti-config-redirect-uris 
#     - key: opencti-admin-email 
#       objectName: opencti-admin-email 
#     - key: opencti-admin-password 
#       objectName: opencti-admin-password 
#     - key: opencti-token 
#       objectName: opencti-token
#     - key: rabbitmq-default-user
#       objectName: rabbitmq-default-user
#     - key: rabbitmq-default-password
#       objectName: rabbitmq-default-password
#     - key: minio-root-user 
#       objectName: minio-root-user 
#     - key: minio-root-password
#       objectName: minio-root-password
#     - key: elasticsearch-user
#       objectName: elasticsearch-user
#     - key: elasticsearch-password
#       objectName: elasticsearch-password
#     - key: alienvault-connector-id
#       objectName: alienvault-connector-id
#     - key: opencti-connector-id
#       objectName: opencti-connector-id
#     - key: alienvault-api-key
#       objectName: alienvault-api-key
#     secretName: opencti-secret                     # name of the Kubernetes secret object
#     type: Opaque                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)  
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "false"          
#     clientID: "90421a2b-00c8-4795-9fd6-2df88ee3724e"
#     keyvaultName: demo-aks-westeu-8c8d
#     tenantId: "bb73082a-b74c-4d39-aec0-41c77d6f4850"
#     objects:  |
#       array:
#         - |
#           objectName: opencti-base-url
#           objectType: secret
#         - |
#           objectName: opencti-config-issuer
#           objectType: secret
#         - |
#           objectName: opencti-config-clientid
#           objectType: secret
#         - |
#           objectName: opencti-config-secret
#           objectType: secret
#         - |
#           objectName: opencti-config-redirect-uris
#           objectType: secret
#         - |
#           objectName: opencti-admin-email
#           objectType: secret
#         - |
#           objectName: opencti-admin-password
#           objectType: secret 
#         - |
#           objectName: opencti-token
#           objectType: secret 
#         - |
#           objectName: rabbitmq-default-user
#           objectType: secret 
#         - |
#           objectName: rabbitmq-default-password
#           objectType: secret 
#         - |
#           objectName: minio-root-user
#           objectType: secret 
#         - |
#           objectName: minio-root-password
#           objectType: secret 
#         - |
#           objectName: elasticsearch-user
#           objectType: secret 
#         - |
#           objectName: elasticsearch-password
#           objectType: secret 
#         - |
#           objectName: alienvault-connector-id
#           objectType: secret 
#         - |
#           objectName: opencti-connector-id
#           objectType: secret
#         - |
#           objectName: alienvault-api-key
#           objectType: secret
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opencti
    # azure.workload.identity/use: "true"
  name: opencti
  namespace: opencti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencti
  strategy: {}
  template:
    metadata:
      labels:
        app: opencti
    spec:
      # serviceAccountName: opencti-sa
      containers:
        - env:
          - name: NODE_OPTIONS
            value: --max-old-space-size=8096
          - name: APP__PORT
            value: "8080"
          - name: APP__BASE_URL
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-base-url
          - name: APP__ADMIN__EMAIL
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-admin-email
          - name: APP__ADMIN__PASSWORD
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-admin-password
          - name: APP__ADMIN__TOKEN
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-token
          - name: APP__APP_LOGS__LOGS_LEVEL
            value: "info"
          - name: REDIS__HOSTNAME
            value: redis.opencti-redis
          - name: REDIS__PORT
            value: "6379"
          - name: ELASTICSEARCH__URL
            value: https://elasticsearch-es-http.opencti-elasticsearch:9200
          - name: ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED
            value: "false"
          - name: ELASTICSEARCH__USERNAME
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: elasticsearch-user
          - name: ELASTICSEARCH__PASSWORD
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: elasticsearch-password
          - name: MINIO__ENDPOINT
            value: minio.opencti-minio
          - name: MINIO__PORT
            value: "9000"
          - name: MINIO__USE_SSL
            value: "false"
          - name: MINIO__ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: minio-root-user
          - name: MINIO__SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: minio-root-password
          - name: RABBITMQ__HOSTNAME
            value: rabbitmq.opencti-rabbitmq
          - name: RABBITMQ__PORT
            value: "5672"
          - name: RABBITMQ__PORT_MANAGEMENT
            value: "15672"
          - name: RABBITMQ__MANAGEMENT_SSL
            value: "false"
          - name: RABBITMQ__USERNAME
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: rabbitmq-default-user
          - name: RABBITMQ__PASSWORD
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: rabbitmq-default-password
          - name: SMTP__HOSTNAME
            value: "localhost"
          - name: SMTP__PORT
            value: "25"
          - name: PROVIDERS__OPENID__STRATEGY
            value: OpenIDConnectStrategy
          - name: PROVIDERS__OPENID__CONFIG__LABEL
            value: Login with OpenID
          - name: PROVIDERS__OPENID__CONFIG__ISSUER
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-config-issuer
          - name: PROVIDERS__OPENID__CONFIG__CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-config-clientid
          - name: PROVIDERS__OPENID__CONFIG__CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-config-secret
          - name: PROVIDERS__OPENID__CONFIG__REDIRECT_URIS
            valueFrom:
              secretKeyRef:
                name: opencti-secret
                key: opencti-config-redirect-uris
          - name: PROVIDERS__LOCAL__STRATEGY
            value: "LocalStrategy"
          image: opencti/platform:5.9.6
          name: opencti
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2048Mi
              cpu: "1500m"
            requests:
              memory: 256Mi
              cpu: 1
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                - "spot"
      #     volumeMounts:
      #     - name: secrets-store01-inline
      #       mountPath: "/mnt/secrets-store"
      #       readOnly: true
      # volumes:
      #   - name: secrets-store01-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "azure-kvname-workload-identity"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: opencti
  namespace: opencti
  labels:
    app: opencti
spec:
  ports:
    - name: "opencti"
      port: 8080
      targetPort: 8080
  selector:
    app: opencti
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencti-ingress
  namespace: opencti
  annotations:
    external-dns.alpha.kubernetes.io/hostname: opencti-ingress.k8s.4t2.no
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/websocket-services: "opencti"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - opencti.4t2.no
    secretName: selfsigned-cert-tls
  rules:
  - host: opencti.4t2.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opencti
            port:
              number: 8080
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: opencti
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: opencti
spec:
  dnsNames:
    - opencti.4t2.no
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned