---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencti-elasticsearch-sa
  namespace: opencti-elasticsearch
  annotations:
    azure.workload.identity/client-id: bb0a6bf4-de13-47a2-abea-e5d29e8ea3b7
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: opencti-elasticsearch-secretprovider # needs to be unique per namespace
  namespace: opencti-elasticsearch
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: username                        # data field to populate
      objectName: elasticsearch-user                       # name of the mounted content to sync; this could be the object name or the object alias
    - key: password                          # data field to populate
      objectName: elasticsearch-password                       # name of the mounted content to sync; this could be the object name or the object alias
    secretName: elasticsearch-auth-secret                    # name of the Kubernetes secret object
    type: kubernetes.io/basic-auth                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "bb0a6bf4-de13-47a2-abea-e5d29e8ea3b7" # Setting this to use workload identity
    keyvaultName: demo-aks-westeu-87c2     # Set to the name of your key vault
    tenantId: "bb73082a-b74c-4d39-aec0-41c77d6f4850"
    objects:  |
      array:
        - |
          objectName: elasticsearch-user
          objectType: secret
        - |
          objectName: elasticsearch-password
          objectType: secret
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: opencti-elasticsearch
spec:
  version: 8.8.0
  auth:
    fileRealm:
    - secretName: elasticsearch-auth-secret
  secureSettings:
  - secretName: elasticsearch-config-secret
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      metadata:
        labels:
          azure.workload.identity/use: true
      spec:
        serviceAccountName: opencti-elasticsearch-sa
        containers:
          - name: elasticsearch
            volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
        volumes:
          - name: secrets-store01-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "opencti-elasticsearch-secretprovider"
    config:
      xpack.ml.enabled: false
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: azurefile-csi-opencti