apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-config-secret
    namespace: opencti-elasticsearch
type: Opaque
stringData:
    bootstrap.password: ENC[AES256_GCM,data:RJu24svucKViC33OoBY24a6isg==,iv:nt/lA/JMPoX1XzKz+TpGdYfe/xydQ2lUrddzudt4xck=,tag:fmITyQ1Q0QXsT+9pYLbnNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-cf2e.vault.azure.net
          name: sops-key
          version: f666d098557742a1bd8f4ed766f04f18
          created_at: "2023-08-03T08:08:59Z"
          enc: ld1Ga1dBCGdcUNQgdEOmM4F124UOTFbClB91WwuTUWa_D1EN1SO3ClNItoLovBdP2c4ZEPUWhxXIm3XRBftUEj5xY1_ooYQyR5NyCUcKP3DM2SGLXaktxG6zhylQ9rbqhIsvHhKee6FRkWSyrwG6xjccu8yfmTHT3Nc_aqcgL2sAENRtl9DYGwKPRt9cKAWKR6dpcvOj2rO0vEjOwXC1AJXOpuUWSiQIfXoJ03dWUXXrxL3sRa-6VnQ69KeidxL6Rrkedf7izqitGTpJ6xQN3W2auFY-peWexzf5OYGubWB-G7dmYBufrR2p15ows8Lk5i4wr6WWihto4PgKL-iovA
    hc_vault: []
    age: []
    lastmodified: "2023-08-03T08:09:00Z"
    mac: ENC[AES256_GCM,data:zkGfDpRVzRDTu+5WQI3eS4QYWMKBbvDWTWkR24zx5+83ibFo4qB0HPjAENBE4pxrEzT0NurDnHZw+4fyy/8NAXYvQF/gDWQ4NU2Sbb5uHyRB3Umd6H9SgYi+LHXep2ZpMbHOzZHnaZqH7AfEb/ftB+ntb9jo2/OFlZXRnG929kA=,iv:1QbjA/8sfgQcP8cNM35f2ZK1klK7Z/TByVYKr8v+paY=,tag:Ck4TDakeTOJjI+txw+JPuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
