---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: opencti-redis
spec:
  containers:
  - name: redis
    image: redis:7.0.11
  volumeMounts:
    - mountPath: /data
      name: localvolume
  volumes:
  - name: localvolume
    emptyDir: {}
