---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  interval: 1h0s
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx
      version: '>=0.18.0'
  interval: 1h0s
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
---